// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1FUKyO00FC0IYXfZzgPCE2SNooQF4jvg',
    appId: '1:406913319321:web:7b451a037012bd6d9bd308',
    messagingSenderId: '406913319321',
    projectId: 'vanmate-56eac',
    authDomain: 'vanmate-56eac.firebaseapp.com',
    storageBucket: 'vanmate-56eac.firebasestorage.app',
    measurementId: 'G-1W5Z7DQTCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgrjvYAChKR-lW30ZUROejwCsB3_ymrI',
    appId: '1:406913319321:android:4bb1aecdb073f9919bd308',
    messagingSenderId: '406913319321',
    projectId: 'vanmate-56eac',
    storageBucket: 'vanmate-56eac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANUrIVXglaIJs-EI2DChFEDcM5vVWqaDs',
    appId: '1:406913319321:ios:8f160fd12da718289bd308',
    messagingSenderId: '406913319321',
    projectId: 'vanmate-56eac',
    storageBucket: 'vanmate-56eac.firebasestorage.app',
    iosBundleId: 'com.davidtyler.vanmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANUrIVXglaIJs-EI2DChFEDcM5vVWqaDs',
    appId: '1:406913319321:ios:8f160fd12da718289bd308',
    messagingSenderId: '406913319321',
    projectId: 'vanmate-56eac',
    storageBucket: 'vanmate-56eac.firebasestorage.app',
    iosBundleId: 'com.davidtyler.vanmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1FUKyO00FC0IYXfZzgPCE2SNooQF4jvg',
    appId: '1:406913319321:web:1a268d5da3395d339bd308',
    messagingSenderId: '406913319321',
    projectId: 'vanmate-56eac',
    authDomain: 'vanmate-56eac.firebaseapp.com',
    storageBucket: 'vanmate-56eac.firebasestorage.app',
    measurementId: 'G-EBWR5LGGFN',
  );

}