import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/van_invoice_draft.dart';
import 'van_text_formatters.dart';
import 'van_business_logo_support.dart';

Future<String> buildVanInvoicePdfPath(VanInvoiceDraft invoice) async {
  final document = pw.Document();
  final logo = await _loadLogo(invoice.logoPath);

  document.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      theme: pw.ThemeData.withFont(),
      build: (context) => [
        _header(invoice, logo),
        pw.SizedBox(height: 18),
        _sectionTitle('Bill to'),
        pw.SizedBox(height: 8),
        _infoBlock([
          invoice.customerName,
          invoice.billingAddress,
          if (invoice.customerPhone.trim().isNotEmpty) invoice.customerPhone,
          if (invoice.customerEmail.trim().isNotEmpty) invoice.customerEmail,
        ]),
        pw.SizedBox(height: 14),
        _sectionTitle('Job'),
        pw.SizedBox(height: 8),
        _infoBlock([invoice.jobReference, invoice.jobDescription]),
        pw.SizedBox(height: 14),
        _sectionTitle('Items'),
        pw.SizedBox(height: 8),
        _itemsTable(invoice),
        if (invoice.mileageCharge > 0 ||
            invoice.estimatedMiles.trim().isNotEmpty) ...[
          pw.SizedBox(height: 14),
          _sectionTitle('Mileage'),
          pw.SizedBox(height: 8),
          _infoBlock([
            if (invoice.estimatedMiles.trim().isNotEmpty)
              'Estimated miles: ${invoice.estimatedMiles}',
            if (invoice.mileageCharge > 0)
              'Mileage charge: ${formatCurrency(invoice.mileageCharge)}',
          ]),
        ],
        pw.SizedBox(height: 14),
        _totalBlock(invoice),
        if (invoice.paymentInstructions.trim().isNotEmpty) ...[
          pw.SizedBox(height: 14),
          _sectionTitle('Payment instructions'),
          pw.SizedBox(height: 8),
          _infoBlock([invoice.paymentInstructions.trim()]),
        ],
        if (invoice.invoiceNotes.trim().isNotEmpty) ...[
          pw.SizedBox(height: 14),
          _sectionTitle('Notes'),
          pw.SizedBox(height: 8),
          _infoBlock([invoice.invoiceNotes.trim()]),
        ],
        pw.SizedBox(height: 24),
        pw.Center(
          child: pw.Text(
            'Generated by Van Mate',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
      ],
    ),
  );

  final directory = await getTemporaryDirectory();
  final fileName = _safeFileName(invoice.invoiceNumber);
  final file = File('${directory.path}${Platform.pathSeparator}$fileName');
  await file.writeAsBytes(await document.save(), flush: true);
  return file.path;
}

Future<pw.MemoryImage?> _loadLogo(String? logoPath) async {
  final resolvedPath = resolveSavedVanBusinessLogoPath(logoPath);
  if (resolvedPath == null) {
    return null;
  }

  try {
    final bytes = await File(resolvedPath).readAsBytes();
    return pw.MemoryImage(bytes);
  } catch (error) {
    if (kDebugMode) {
      debugPrint('Van Mate PDF logo load failed: $error');
    }
    return null;
  }
}

pw.Widget _header(VanInvoiceDraft invoice, pw.MemoryImage? logo) {
  return pw.Row(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      if (logo != null) ...[
        pw.Container(
          width: 64,
          height: 64,
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(12),
            border: pw.Border.all(color: PdfColors.grey300),
          ),
          child: pw.Padding(
            padding: const pw.EdgeInsets.all(6),
            child: pw.Image(logo, fit: pw.BoxFit.contain),
          ),
        ),
        pw.SizedBox(width: 12),
      ],
      pw.Expanded(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              invoice.businessName,
              style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
            ),
            if (invoice.contactName.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(invoice.contactName),
            ],
            if (invoice.businessAddress.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(invoice.businessAddress),
            ],
            if (invoice.phone.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(invoice.phone),
            ],
            if (invoice.email.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(invoice.email),
            ],
          ],
        ),
      ),
      pw.SizedBox(width: 16),
      pw.Container(
        width: 150,
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          borderRadius: pw.BorderRadius.circular(12),
          color: PdfColors.grey100,
          border: pw.Border.all(color: PdfColors.grey300),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Invoice No: ${invoice.invoiceNumber}',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 6),
            pw.Text('Date: ${invoice.invoiceDate}'),
            pw.SizedBox(height: 4),
            pw.Text('Due: ${invoice.dueDate}'),
          ],
        ),
      ),
    ],
  );
}

pw.Widget _sectionTitle(String title) {
  return pw.Text(
    title,
    style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
  );
}

pw.Widget _infoBlock(List<String> lines) {
  return pw.Container(
    width: double.infinity,
    padding: const pw.EdgeInsets.all(12),
    decoration: pw.BoxDecoration(
      color: PdfColors.grey100,
      borderRadius: pw.BorderRadius.circular(12),
      border: pw.Border.all(color: PdfColors.grey300),
    ),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        for (var i = 0; i < lines.length; i++) ...[
          pw.Text(lines[i]),
          if (i < lines.length - 1) pw.SizedBox(height: 4),
        ],
      ],
    ),
  );
}

pw.Widget _itemsTable(VanInvoiceDraft invoice) {
  final rows = invoice.lineItems.isEmpty
      ? [
          ['No items added', '', '', formatCurrency(0)],
        ]
      : invoice.lineItems
            .map(
              (item) => [
                item.description,
                item.quantity.toString(),
                formatCurrency(item.amount),
                formatCurrency(item.total),
              ],
            )
            .toList();

  return pw.Table(
    border: pw.TableBorder.all(color: PdfColors.grey300),
    columnWidths: const {
      0: pw.FlexColumnWidth(3),
      1: pw.FlexColumnWidth(0.8),
      2: pw.FlexColumnWidth(1.1),
      3: pw.FlexColumnWidth(1.1),
    },
    children: [
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: [
          _tableCell('Description', bold: true),
          _tableCell('Qty', bold: true),
          _tableCell('Amount', bold: true),
          _tableCell('Total', bold: true),
        ],
      ),
      for (final row in rows)
        pw.TableRow(
          children: [
            _tableCell(row[0]),
            _tableCell(row[1], alignRight: true),
            _tableCell(row[2], alignRight: true),
            _tableCell(row[3], alignRight: true),
          ],
        ),
    ],
  );
}

pw.Widget _tableCell(
  String value, {
  bool bold = false,
  bool alignRight = false,
}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.all(8),
    child: pw.Align(
      alignment: alignRight
          ? pw.Alignment.centerRight
          : pw.Alignment.centerLeft,
      child: pw.Text(
        value,
        style: pw.TextStyle(
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    ),
  );
}

pw.Widget _totalBlock(VanInvoiceDraft invoice) {
  return pw.Container(
    width: double.infinity,
    padding: const pw.EdgeInsets.all(12),
    decoration: pw.BoxDecoration(
      color: PdfColors.grey100,
      borderRadius: pw.BorderRadius.circular(12),
      border: pw.Border.all(color: PdfColors.grey300),
    ),
    child: pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Total due',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14),
        ),
        pw.Text(
          formatCurrency(invoice.totalDue),
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16),
        ),
      ],
    ),
  );
}

String _safeFileName(String invoiceNumber) {
  final trimmed = invoiceNumber.trim();
  final baseName = trimmed.isEmpty
      ? 'VanMate-Invoice-${DateTime.now().millisecondsSinceEpoch}'
      : 'VanMate-Invoice-${trimmed.replaceAll(RegExp(r'[\\/:*?"<>|]+'), '-')}';
  final normalized = baseName.replaceAll(RegExp(r'\s+'), '-');
  return '$normalized.pdf';
}
