import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/van_job_report.dart';
import 'van_business_logo_support.dart';

Future<String> buildVanJobReportPdfPath(VanReportDocument report) async {
  final document = pw.Document();
  final logo = await _loadLogo(
    report.businessProfile.logoPath,
    report.businessProfile.logoUrl,
  );

  document.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => [
        _header(report, logo),
        pw.SizedBox(height: 18),
        _summaryCard(report),
        for (final section in report.sections) ...[
          pw.SizedBox(height: 18),
          _sectionTitle(section.title),
          pw.SizedBox(height: 8),
          _tableSection(section),
        ],
        pw.SizedBox(height: 24),
        pw.Center(
          child: pw.Text(
            'Generated by Van Mate',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
      ],
    ),
  );

  final directory = await getTemporaryDirectory();
  final fileName = _safeFileName(report);
  final file = File('${directory.path}${Platform.pathSeparator}$fileName');
  await file.writeAsBytes(await document.save(), flush: true);
  return file.path;
}

Future<pw.MemoryImage?> _loadLogo(String? logoPath, String? logoUrl) async {
  final resolvedLogoUrl = resolveSavedVanBusinessLogoUrl(logoUrl);
  if (resolvedLogoUrl != null) {
    final networkLogo = await _loadLogoFromUrl(resolvedLogoUrl);
    if (networkLogo != null) {
      return networkLogo;
    }
  }

  final resolvedPath = resolveSavedVanBusinessLogoPath(logoPath);
  if (resolvedPath == null) {
    return null;
  }

  try {
    final bytes = await File(resolvedPath).readAsBytes();
    return pw.MemoryImage(bytes);
  } catch (error) {
    if (kDebugMode) {
      debugPrint('Van Mate report logo load failed: $error');
    }
    return null;
  }
}

Future<pw.MemoryImage?> _loadLogoFromUrl(String logoUrl) async {
  HttpClient? client;
  try {
    client = HttpClient();
    final request = await client.getUrl(Uri.parse(logoUrl));
    final response = await request.close();
    if (response.statusCode < 200 || response.statusCode >= 300) {
      return null;
    }
    final bytes = await consolidateHttpClientResponseBytes(response);
    if (bytes.isEmpty) {
      return null;
    }
    return pw.MemoryImage(bytes);
  } catch (error) {
    if (kDebugMode) {
      debugPrint('Van Mate report logo URL load failed: $error');
    }
    return null;
  } finally {
    client?.close(force: true);
  }
}

pw.Widget _header(VanReportDocument report, pw.MemoryImage? logo) {
  return pw.Row(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      if (logo != null) ...[
        pw.Container(
          width: 64,
          height: 64,
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(12),
            border: pw.Border.all(color: PdfColors.grey300),
          ),
          child: pw.Padding(
            padding: const pw.EdgeInsets.all(6),
            child: pw.Image(logo, fit: pw.BoxFit.contain),
          ),
        ),
        pw.SizedBox(width: 12),
      ],
      pw.Expanded(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              report.reportTitle,
              style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text('Date range: ${report.dateRangeLabel}'),
            pw.SizedBox(height: 4),
            pw.Text('Generated: ${report.generatedDateLabel}'),
          ],
        ),
      ),
      pw.SizedBox(width: 16),
      pw.Container(
        width: 170,
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          borderRadius: pw.BorderRadius.circular(12),
          color: PdfColors.grey100,
          border: pw.Border.all(color: PdfColors.grey300),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              report.businessProfile.businessName,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            if (report.businessProfile.contactName.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.contactName),
            ],
            if (report.businessProfile.phone.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.phone),
            ],
            if (report.businessProfile.email.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.email),
            ],
            if (report.businessProfile.businessAddress.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.businessAddress),
            ],
          ],
        ),
      ),
    ],
  );
}

pw.Widget _summaryCard(VanReportDocument report) {
  return pw.Container(
    width: double.infinity,
    padding: const pw.EdgeInsets.all(14),
    decoration: pw.BoxDecoration(
      color: PdfColors.grey100,
      borderRadius: pw.BorderRadius.circular(14),
      border: pw.Border.all(color: PdfColors.grey300),
    ),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Summary totals',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        for (var i = 0; i < report.summaryLines.length; i++) ...[
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Expanded(child: pw.Text(report.summaryLines[i].label)),
              pw.SizedBox(width: 12),
              pw.Text(
                report.summaryLines[i].value,
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
            ],
          ),
          if (i < report.summaryLines.length - 1) pw.SizedBox(height: 6),
        ],
      ],
    ),
  );
}

pw.Widget _sectionTitle(String title) {
  return pw.Text(
    title,
    style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
  );
}

pw.Widget _tableSection(VanReportTableSection section) {
  final rows = section.rows.isEmpty
      ? [
          List<String>.filled(section.headers.length, '').toList()
            ..[0] = 'No data',
        ]
      : section.rows;

  return pw.Table(
    border: pw.TableBorder.all(color: PdfColors.grey300),
    children: [
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: [
          for (final header in section.headers) _tableCell(header, bold: true),
        ],
      ),
      for (final row in rows)
        pw.TableRow(children: [for (final value in row) _tableCell(value)]),
    ],
  );
}

pw.Widget _tableCell(String value, {bool bold = false}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.all(8),
    child: pw.Text(
      value,
      style: pw.TextStyle(
        fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        fontSize: 9.5,
      ),
    ),
  );
}

String _safeFileName(VanReportDocument report) {
  final safeTitle = report.reportTitle
      .replaceAll(RegExp(r'[^A-Za-z0-9]+'), '-')
      .replaceAll(RegExp(r'-+'), '-')
      .replaceAll(RegExp(r'^-|-$'), '');
  return 'VanMate-${safeTitle.isEmpty ? 'Report' : safeTitle}.pdf';
}
