import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/van_job_report.dart';
import 'van_text_formatters.dart';
import 'van_business_logo_support.dart';

Future<String> buildVanJobReportPdfPath(VanJobReportData report) async {
  final document = pw.Document();
  final logo = await _loadLogo(report.businessProfile.logoPath);

  document.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      theme: pw.ThemeData.withFont(),
      build: (context) => [
        _header(report, logo),
        pw.SizedBox(height: 18),
        _summaryCard(report),
        pw.SizedBox(height: 18),
        _sectionTitle('Jobs'),
        pw.SizedBox(height: 8),
        _jobsTable(report),
        if (report.entries.any(
          (entry) => (entry.notes ?? '').trim().isNotEmpty,
        )) ...[
          pw.SizedBox(height: 18),
          _sectionTitle('Notes'),
          pw.SizedBox(height: 8),
          _notesList(report),
        ],
        pw.SizedBox(height: 24),
        pw.Center(
          child: pw.Text(
            'Generated by Van Mate',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
      ],
    ),
  );

  final directory = await getTemporaryDirectory();
  final fileName = _safeFileName(report);
  final file = File('${directory.path}${Platform.pathSeparator}$fileName');
  await file.writeAsBytes(await document.save(), flush: true);
  return file.path;
}

Future<pw.MemoryImage?> _loadLogo(String? logoPath) async {
  final resolvedPath = resolveSavedVanBusinessLogoPath(logoPath);
  if (resolvedPath == null) {
    return null;
  }

  try {
    final bytes = await File(resolvedPath).readAsBytes();
    return pw.MemoryImage(bytes);
  } catch (error) {
    if (kDebugMode) {
      debugPrint('Van Mate job report logo load failed: $error');
    }
    return null;
  }
}

pw.Widget _header(VanJobReportData report, pw.MemoryImage? logo) {
  return pw.Row(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      if (logo != null) ...[
        pw.Container(
          width: 64,
          height: 64,
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(12),
            border: pw.Border.all(color: PdfColors.grey300),
          ),
          child: pw.Padding(
            padding: const pw.EdgeInsets.all(6),
            child: pw.Image(logo, fit: pw.BoxFit.contain),
          ),
        ),
        pw.SizedBox(width: 12),
      ],
      pw.Expanded(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Van Mate Job Report',
              style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text(report.previewTitle),
            pw.SizedBox(height: 4),
            pw.Text(report.previewSubtitle),
          ],
        ),
      ),
      pw.SizedBox(width: 16),
      pw.Container(
        width: 170,
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          borderRadius: pw.BorderRadius.circular(12),
          color: PdfColors.grey100,
          border: pw.Border.all(color: PdfColors.grey300),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              report.businessProfile.businessName,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            if (report.businessProfile.contactName.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.contactName),
            ],
            if (report.businessProfile.phone.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.phone),
            ],
            if (report.businessProfile.email.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.email),
            ],
            if (report.businessProfile.businessAddress.trim().isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(report.businessProfile.businessAddress),
            ],
          ],
        ),
      ),
    ],
  );
}

pw.Widget _summaryCard(VanJobReportData report) {
  return pw.Container(
    width: double.infinity,
    padding: const pw.EdgeInsets.all(14),
    decoration: pw.BoxDecoration(
      color: PdfColors.grey100,
      borderRadius: pw.BorderRadius.circular(14),
      border: pw.Border.all(color: PdfColors.grey300),
    ),
    child: pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Completed jobs: ${report.completedJobsCount}',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 4),
              pw.Text('Quotes sent: ${report.quotesSentCount}'),
              pw.SizedBox(height: 4),
              pw.Text('Invoices created: ${report.invoicesCreatedCount}'),
              pw.SizedBox(height: 4),
              pw.Text('Total quoted: ${report.totalQuotedText}'),
              pw.SizedBox(height: 4),
              pw.Text('Paid: ${report.totalPaidText}'),
            ],
          ),
        ),
        pw.SizedBox(width: 18),
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Total invoiced',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(
                report.totalInvoicedText,
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text('Outstanding: ${report.totalOutstandingText}'),
              pw.SizedBox(height: 4),
              pw.Text('Total miles: ${report.totalMilesText}'),
              pw.SizedBox(height: 4),
              pw.Text(
                'Mileage charges included: ${report.totalMileageChargesText}',
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Completed job value: ${report.totalCompletedJobValueText}',
              ),
            ],
          ),
        ),
      ],
    ),
  );
}

pw.Widget _sectionTitle(String title) {
  return pw.Text(
    title,
    style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
  );
}

pw.Widget _jobsTable(VanJobReportData report) {
  final rows = report.entries.isEmpty
      ? [
          ['No completed jobs', '', '', '', '', '', '', ''],
        ]
      : report.entries
            .map(
              (entry) => [
                entry.customerName,
                entry.jobTitle,
                entry.reportDateSummary,
                entry.quoteLabel.replaceFirst('Quote: ', ''),
                entry.invoiceLabel.replaceFirst('Invoice: ', ''),
                entry.hasInvoice
                    ? formatCurrency(entry.invoiceTotal ?? 0)
                    : '-',
                entry.estimatedMiles == null
                    ? '-'
                    : formatVanMileage(entry.estimatedMiles ?? 0),
                entry.exactPinSaved ? 'Saved' : 'Not saved',
              ],
            )
            .toList();

  return pw.Table(
    border: pw.TableBorder.all(color: PdfColors.grey300),
    columnWidths: const {
      0: pw.FlexColumnWidth(1.6),
      1: pw.FlexColumnWidth(1.4),
      2: pw.FlexColumnWidth(1.0),
      3: pw.FlexColumnWidth(0.9),
      4: pw.FlexColumnWidth(1.0),
      5: pw.FlexColumnWidth(0.9),
      6: pw.FlexColumnWidth(0.8),
      7: pw.FlexColumnWidth(0.8),
    },
    children: [
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: [
          _tableCell('Customer', bold: true),
          _tableCell('Job', bold: true),
          _tableCell('Completed', bold: true),
          _tableCell('Quote', bold: true),
          _tableCell('Invoice', bold: true),
          _tableCell('Total', bold: true),
          _tableCell('Miles', bold: true),
          _tableCell('Pin', bold: true),
        ],
      ),
      for (final row in rows)
        pw.TableRow(
          children: [
            _tableCell(row[0]),
            _tableCell(row[1]),
            _tableCell(row[2]),
            _tableCell(row[3], alignRight: true),
            _tableCell(row[4], alignRight: true),
            _tableCell(row[5], alignRight: true),
            _tableCell(row[6], alignRight: true),
            _tableCell(row[7]),
          ],
        ),
    ],
  );
}

pw.Widget _notesList(VanJobReportData report) {
  final notes = report.entries
      .where((entry) => (entry.notes ?? '').trim().isNotEmpty)
      .map(
        (entry) =>
            '${sanitizeVanText(entry.customerName).trim()} - ${sanitizeVanText(entry.jobTitle).trim()}: ${sanitizeVanText(entry.notes).trim()}',
      )
      .toList();

  return pw.Container(
    width: double.infinity,
    padding: const pw.EdgeInsets.all(12),
    decoration: pw.BoxDecoration(
      color: PdfColors.grey100,
      borderRadius: pw.BorderRadius.circular(12),
      border: pw.Border.all(color: PdfColors.grey300),
    ),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        for (var i = 0; i < notes.length; i++) ...[
          pw.Text(notes[i]),
          if (i < notes.length - 1) pw.SizedBox(height: 6),
        ],
      ],
    ),
  );
}

pw.Widget _tableCell(
  String value, {
  bool bold = false,
  bool alignRight = false,
}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.all(8),
    child: pw.Align(
      alignment: alignRight
          ? pw.Alignment.centerRight
          : pw.Alignment.centerLeft,
      child: pw.Text(
        value,
        style: pw.TextStyle(
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
          fontSize: 9.5,
        ),
      ),
    ),
  );
}

String _safeFileName(VanJobReportData report) {
  final suffix = report.range == VanJobReportRange.today
      ? formatVanDateForFile(report.rangeStart)
      : 'Week-${formatVanDateForFile(report.rangeStart)}';
  return 'VanMate-Job-Report-$suffix.pdf';
}
